### ISSUE TITLE
Websocket connection failure rapid reload

### ISSUE THREAD

**Issue by gstewart86** [workfloworchestrator/orchestrator-core-gui#127]
After a recent update, the client appears to be failing to connect to establish a websocket connection every few seconds. The page flickers as though its quickly reloading:

https://user-images.githubusercontent.com/10198391/174185848-f7834d45-005b-44bf-b88c-6df7bf227291.mov

 on the backend, we see the following errors each time:
```2022-06-16 22:18:01 [info     ] ('192.168.176.5', 60636) - "WebSocket /ws" 403 [uvicorn.error] 
INFO:     connection failed (403 Forbidden)
2022-06-16 22:18:01 [info     ] connection failed (403 Forbidden) [uvicorn.error] 
INFO:     connection closed
2022-06-16 22:18:01 [info     ] connection closed              [uvicorn.error] 
```

I do see in the docs there appears to be a possibly related change, referencing a `FAST_REFRESH` setting, but I do have that in the `.env.local` file, and it appears to make no difference
![image](https://user-images.githubusercontent.com/10198391/174186844-411c51da-7a90-478e-afdd-d06711353fed.png)

Is this something you've seen before?

**Comment by pboers1988** [comment]
@acidjunk @tjeerddie Any thoughts on this?

**Comment by acidjunk** [comment]
Is this occurring in the dev server? Or in a prod build? Looks like a local development server based on the movie.

I only had it whilst in dev mode: and then only after I changed some src code; then the hot reload kicks in and it would occasionally trigger the websocket reconnect. I suspect that the way React does the hot reload doesn't work well with the "service" lifecycle that implements the websocket (and handles the auth/token stuff). This somehow lifes outside the app lifecycle. So it's probably a `SetInterval()` that handles the ping/pong that doesn't gets cancelled when reloading.

For me this was solved by adding the FAST_REFRESH=false.
or by reloading a page by hand after the devserver reloaded after a change.
AFAIK; nor problems in prod builds; the changes was actually done because we had a problem in production that the websocket would stop working after approx.. 5 minutes; and it would fall back on Polling via REST which had all kind of visible side effects. (flickering and reset of table states after a filter)

I can create a ticket for this: and implement websocket (on a component level) by using the https://www.npmjs.com/package/react-use-websocket : but then we probably also need to refactor some class based components to function based.

**Comment by acidjunk** [comment]
I had a look at your settings, these are mine:
```
BACKEND_URL="http://localhost:8080"
REACT_APP_BACKEND_URL="http://127.0.0.1:8080"
```

You `REACT_APP_BACKEND_URL` seems to point to frontend, instead of backend. Do you see open websockets at all?

**Comment by acidjunk** [comment]
Can you try with correct `REACT_APP_BACKEND_URL` ?

This seems to indicate no webscoket connection at all:

<img width="287" alt="Screenshot 2022-06-23 at 11 59 09" src="https://user-images.githubusercontent.com/685002/175273090-74c3b1ba-02b5-415b-befd-597606f68445.png">

**Comment by gstewart86** [comment]
it is a local develop build. This is what the env looks like today:
```
docker ps --filter "name=orchestrator" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.ID}}\t{{.Image}}'
NAMES                  STATUS          PORTS                     CONTAINER ID   IMAGE
orchestrator-client    Up 17 minutes   0.0.0.0:3000->3000/tcp    c52b44bee1f5   node:14
orchestrator-backend   Up 12 minutes   0.0.0.0:8080->8080/tcp    f6481220ed96   orchestrator_local:latest
```

Changing the vars to the ones you suggest produces the following error from the frontend container:
 ```
Proxy error: Could not proxy request /static/js/vendors~main.chunk.js from 127.0.0.1:3000 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
proof env vars are there:
```
❯ docker exec -it orchestrator-client bash
root@772cb1798e0a:/# env | grep URL
REACT_APP_OAUTH2_OPENID_CONNECT_URL=
BACKEND_URL=http://localhost:8080
REACT_APP_BACKEND_URL=http://127.0.0.1:8080
```


I did manage to make it work with the following settings in the docker compose file
```
    environment:
      BACKEND_URL: "http://${BACKEND_CONTAINER_NAME}:8080"
      REACT_APP_BACKEND_URL: "http://127.0.0.1:3000"
```
where `BACKEND_CONTAINER_NAME` ends up being `orchestrator-backend`
The page no longer seems to sporadically reload like the initial video, however the WS connection breaks shortly after startup
![image](https://user-images.githubusercontent.com/10198391/175615566-dc8e96f3-e8b2-4fe9-bf71-9e20b7ac1782.png)

**Comment by acidjunk** [comment]
BACKEND_URL and REACT_APP_BACKEND_URL should point to the same address. 
(we should probably rename one to WEBSOCKET_URL or something more obvious)

The invalid frame header: indicates no websocket connection at all. 

Here you can see how the console in the browser should look and the network tab whilst inspecting:
<img width="945" alt="Schermafbeelding 2022-06-25 om 05 19 06" src="https://user-images.githubusercontent.com/685002/175756259-22fba495-53f0-43e4-b415-5246d6dd4c58.png">

<img width="806" alt="Schermafbeelding 2022-06-25 om 05 19 58" src="https://user-images.githubusercontent.com/685002/175756266-94dfe9d4-d1df-45b5-aee1-03a8f7ac4373.png">




BTW: At Surf we don't use auth whilst developing. Auth is added only for production/staging.

**Comment by gstewart86** [comment]
so, using the same settings you list above:
![image](https://user-images.githubusercontent.com/10198391/176008585-844325ba-21be-4655-ba7b-48f7232c9fa4.png)

I do see both websocket connections (i think?) but then errors continue to pile up immediately after.
![image](https://user-images.githubusercontent.com/10198391/176008389-381d6a0d-81fc-48d8-be5e-02bca5a4acb0.png)

![image](https://user-images.githubusercontent.com/10198391/176012162-926b5381-49cd-4c0f-b1b4-23be7a4f83d8.png)

also these proxy errors in the frontend container continue:
 ```
Proxy error: Could not proxy request /static/js/vendors~main.chunk.js from 127.0.0.1:3000 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

Why would the socket retry so consistently?

**Comment by gstewart86** [comment]
On further experimentation, it appears this socket will fail if i start both containers up at the same time. I'm wondering if this isn't related to some kind of timing issue on startup. In any case, it appears that restarting the frontend container at that point will result in successful, stable websocket connections:
![image](https://user-images.githubusercontent.com/10198391/176091166-cc188baf-5eb6-4aaf-b640-eccfc8cfe564.png)

However, as soon as I enable the dark theme, websocket connections begin to fail once more:
![image](https://user-images.githubusercontent.com/10198391/176091258-f742b668-74e1-4ead-a7f1-a7a98d4d3735.png)

**Comment by gstewart86** [comment]
I realize I've left this open - @acidjunk I think you gave me what I needed, thank you for the feedback! I'll resolve this issue now.
